import { auth } from '@/lib/auth';
import { redirect } from 'next/navigation';
import Link from 'next/link';
import { prisma } from '@/lib/db';
import GSAPWrapper from '@/components/shared/GSAPWrapper';

export default async function MyDataPage() {
  const session = await auth();
  if (!session?.user?.id) redirect('/login');

  const userId = session.user.id;
  const cityId = session.user.cityId;
  const role = session.user.role;

  // Fetch all user-specific data in parallel
  const [myScenarios, myInterventions, myReports, cityNeighborhoods, cityStats] =
    await Promise.all([
      // Scenarios created by this user
      cityId
        ? prisma.scenario.findMany({
            where: { cityId, createdById: userId },
            include: {
              scenarioInterventions: true,
              simulationResults: { orderBy: { runAt: 'desc' }, take: 1 },
            },
            orderBy: { createdAt: 'desc' },
            take: 10,
          })
        : Promise.resolve([]),

      // Interventions proposed by this user
      cityId
        ? prisma.intervention.findMany({
            where: { cityId, proposedById: userId },
            include: { neighborhood: { select: { name: true } } },
            orderBy: { createdAt: 'desc' },
            take: 10,
          })
        : Promise.resolve([]),

      // Reports generated by this user
      cityId
        ? prisma.report.findMany({
            where: { cityId, generatedById: userId },
            orderBy: { generatedAt: 'desc' },
            take: 10,
          })
        : Promise.resolve([]),

      // All neighborhoods for city-level overview
      cityId
        ? prisma.neighborhood.findMany({
            where: { cityId },
            include: {
              heatMeasurements: { orderBy: { measurementDate: 'desc' }, take: 1 },
            },
            orderBy: { name: 'asc' },
          })
        : Promise.resolve([]),

      // City-wide counts
      cityId
        ? Promise.all([
            prisma.scenario.count({ where: { cityId } }),
            prisma.intervention.count({ where: { cityId } }),
            prisma.neighborhood.count({ where: { cityId } }),
          ])
        : Promise.resolve([0, 0, 0] as [number, number, number]),
    ]);

  const [totalScenarios, totalInterventions, totalNeighborhoods] = cityStats as [
    number,
    number,
    number,
  ];

  const criticalNeighborhoods = cityNeighborhoods.filter(
    (n) => n.vulnerabilityLevel === 'CRITICAL',
  );
  const highNeighborhoods = cityNeighborhoods.filter((n) => n.vulnerabilityLevel === 'HIGH');

  const avgTemp =
    cityNeighborhoods.length > 0
      ? cityNeighborhoods.reduce((sum, n) => {
          return sum + (n.heatMeasurements[0]?.avgTempCelsius ?? 0);
        }, 0) / cityNeighborhoods.filter((n) => n.heatMeasurements.length > 0).length || 0
      : 0;

  function statusColor(status: string) {
    switch (status) {
      case 'APPROVED':
      case 'ACTIVE':
      case 'COMPLETED':
        return { color: 'var(--low)', bg: '#22c55e1a', border: '#22c55e4d' };
      case 'SUBMITTED':
      case 'IN_PROGRESS':
        return { color: 'var(--high)', bg: '#f973161a', border: '#f973164d' };
      case 'NEEDS_REVISION':
      case 'REJECTED':
        return { color: 'var(--critical)', bg: '#ef44441a', border: '#ef44444d' };
      default:
        return {
          color: 'var(--text-tertiary)',
          bg: 'var(--bg-elevated)',
          border: 'var(--border-strong)',
        };
    }
  }

  return (
    <div className="flex flex-col gap-8">
      {/* Page header */}
      <GSAPWrapper animation="slideUp" duration={0.5}>
        <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
        <div>
          <div className="flex items-center gap-1.5 mb-2">
            <span
              className="material-symbols-outlined text-[var(--text-tertiary)] text-sm"
              style={{ fontVariationSettings: "'FILL' 1" }}
            >
              person
            </span>
            <span className="text-[10px] font-medium uppercase tracking-[0.06em] text-[var(--text-tertiary)]">
              My Data
            </span>
          </div>
          <h1 className="text-2xl font-bold tracking-tight text-[var(--text-primary)]">
            {session.user.name ?? 'Your Dashboard'}
          </h1>
          <p className="mt-0.5 text-sm text-[var(--text-secondary)]">
            All your scenarios, interventions, reports, and city overview in one place.
          </p>
        </div>
          <div className="flex items-center gap-2">
          <Link
            href="/map"
            className="inline-flex items-center gap-1.5 h-9 px-4 text-sm font-medium text-[var(--text-secondary)] border border-[var(--border-strong)] rounded-md hover:bg-[var(--bg-elevated)] transition-colors"
          >
            <span className="material-symbols-outlined text-sm">map</span>
            View Map
          </Link>
        </div>
        </div>
      </GSAPWrapper>

      {/* Profile card + role */}
      <GSAPWrapper animation="slideUp" delay={0.1} duration={0.5} stagger>
        <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
        <div className="md:col-span-1 bg-[var(--bg-surface)] border border-[var(--border)] rounded-lg p-5 flex flex-col gap-3">
          <div className="w-10 h-10 rounded-full bg-[var(--green-500)]/20 border border-[var(--green-500)]/30 flex items-center justify-center">
            <span
              className="material-symbols-outlined text-[var(--green-400)] text-xl"
              style={{ fontVariationSettings: "'FILL' 1" }}
            >
              person
            </span>
          </div>
          <div>
            <div className="text-sm font-semibold text-[var(--text-primary)]">
              {session.user.name ?? '—'}
            </div>
            <div className="text-xs text-[var(--text-secondary)] mt-0.5 truncate">
              {session.user.email}
            </div>
          </div>
          <span
            className="self-start text-[10px] font-semibold uppercase tracking-[0.05em] border rounded px-2 py-0.5"
            style={{ color: 'var(--green-400)', borderColor: '#22c55e4d', backgroundColor: '#22c55e1a' }}
          >
            {role?.replace(/_/g, ' ')}
          </span>
        </div>

        {[
          {
            label: 'My Scenarios',
            value: myScenarios.length,
            total: totalScenarios,
            icon: 'compare_arrows',
            color: 'var(--info)',
          },
          {
            label: 'My Interventions',
            value: myInterventions.length,
            total: totalInterventions,
            icon: 'construction',
            color: 'var(--high)',
          },
          {
            label: 'City Neighborhoods',
            value: cityNeighborhoods.length,
            total: totalNeighborhoods,
            icon: 'location_city',
            color: 'var(--green-400)',
          },
        ].map((stat) => (
          <div
            key={stat.label}
            className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-lg p-5 flex flex-col justify-between"
          >
            <div className="flex items-center gap-2 mb-3">
              <span
                className="material-symbols-outlined text-base"
                style={{ color: stat.color, fontVariationSettings: "'FILL' 1" }}
              >
                {stat.icon}
              </span>
              <span className="text-[10px] font-medium uppercase tracking-[0.06em] text-[var(--text-tertiary)]">
                {stat.label}
              </span>
            </div>
            <div className="text-3xl font-bold tabular-nums text-[var(--text-primary)]">
              {stat.value}
            </div>
            <div className="text-[11px] text-[var(--text-tertiary)] mt-1">
              of {stat.total} city-wide
            </div>
          </div>
        ))}
      </div>
      </GSAPWrapper>

      {/* City heat overview */}
      {cityNeighborhoods.length > 0 && (
        <GSAPWrapper animation="slideUp" delay={0.2} duration={0.5}>
        <div>
          <div className="flex items-center gap-1.5 mb-3">
            <span
              className="material-symbols-outlined text-[var(--text-tertiary)] text-sm"
              style={{ fontVariationSettings: "'FILL' 1" }}
            >
              thermostat
            </span>
            <h2 className="text-[11px] font-medium uppercase tracking-[0.06em] text-[var(--text-tertiary)]">
              City Heat Overview
            </h2>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-4">
            <div className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-lg p-4">
              <div className="text-[10px] uppercase tracking-[0.06em] text-[var(--text-tertiary)]">Avg Temperature</div>
              <div className="mt-1 text-2xl font-bold text-[var(--high)]">
                {avgTemp > 0 ? `${avgTemp.toFixed(1)}°C` : '—'}
              </div>
            </div>
            <div className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-lg p-4">
              <div className="text-[10px] uppercase tracking-[0.06em] text-[var(--text-tertiary)]">Critical Zones</div>
              <div className="mt-1 text-2xl font-bold text-[var(--critical)]">
                {criticalNeighborhoods.length}
              </div>
            </div>
            <div className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-lg p-4">
              <div className="text-[10px] uppercase tracking-[0.06em] text-[var(--text-tertiary)]">High-Risk Zones</div>
              <div className="mt-1 text-2xl font-bold text-[var(--high)]">
                {highNeighborhoods.length}
              </div>
            </div>
            <div className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-lg p-4">
              <div className="text-[10px] uppercase tracking-[0.06em] text-[var(--text-tertiary)]">Total Areas</div>
              <div className="mt-1 text-2xl font-bold text-[var(--text-primary)]">
                {cityNeighborhoods.length}
              </div>
            </div>
          </div>

          {/* Neighborhood heat table */}
          {cityNeighborhoods.length > 0 && (
            <div className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-lg overflow-hidden">
              <div className="px-4 py-3 border-b border-[var(--border)] flex items-center justify-between">
                <span className="text-xs font-semibold text-[var(--text-primary)]">Neighborhood Heat Status</span>
                <Link href="/dashboard/neighborhoods" className="text-[11px] text-[var(--text-tertiary)] hover:text-[var(--text-primary)] transition-colors">
                  View all →
                </Link>
              </div>
              <div className="divide-y divide-[var(--border)]">
                {cityNeighborhoods.slice(0, 8).map((n) => {
                  const temp = n.heatMeasurements[0]?.avgTempCelsius;
                  const level = n.vulnerabilityLevel || 'UNKNOWN';
                  const colors: Record<string, string> = {
                    CRITICAL: '#ef4444',
                    HIGH: '#f97316',
                    MODERATE: '#eab308',
                    LOW: '#22c55e',
                  };
                  const c = colors[level] || '#a3a3a3';
                  return (
                    <div key={n.id} className="flex items-center px-4 py-2.5 hover:bg-[var(--bg-elevated)] transition-colors">
                      <div className="flex-1 min-w-0">
                        <div className="text-xs font-medium text-[var(--text-primary)] truncate">{n.name}</div>
                        <div className="text-[10px] text-[var(--text-tertiary)]">
                          Pop. {n.population?.toLocaleString() ?? '—'}
                        </div>
                      </div>
                      <div className="flex items-center gap-3">
                        <span className="text-xs font-semibold tabular-nums" style={{ color: c }}>
                          {temp != null ? `${temp.toFixed(1)}°C` : '—'}
                        </span>
                        <span
                          className="text-[10px] font-semibold uppercase px-1.5 py-0.5 rounded border"
                          style={{ color: c, backgroundColor: `${c}1a`, borderColor: `${c}4d` }}
                        >
                          {level}
                        </span>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>
        </GSAPWrapper>
      )}

      <GSAPWrapper animation="slideUp" delay={0.3} duration={0.5}>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* My Scenarios */}
        <div>
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-1.5">
              <span
                className="material-symbols-outlined text-[var(--text-tertiary)] text-sm"
                style={{ fontVariationSettings: "'FILL' 1" }}
              >
                compare_arrows
              </span>
              <h2 className="text-[11px] font-medium uppercase tracking-[0.06em] text-[var(--text-tertiary)]">
                My Scenarios
              </h2>
            </div>
            <Link
              href="/dashboard/scenarios"
              className="text-[11px] text-[var(--text-tertiary)] hover:text-[var(--text-primary)] transition-colors"
            >
              View all →
            </Link>
          </div>

          {myScenarios.length === 0 ? (
            <div className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-lg p-6 text-center">
              <span
                className="material-symbols-outlined text-2xl text-[var(--text-tertiary)]"
                style={{ fontVariationSettings: "'FILL' 1" }}
              >
                compare_arrows
              </span>
              <p className="mt-2 text-xs text-[var(--text-secondary)]">No scenarios created yet.</p>
              <Link
                href="/dashboard/scenarios/new"
                className="mt-3 inline-flex items-center gap-1 h-8 px-3 text-xs font-medium bg-[var(--green-500)] text-white rounded-md hover:bg-[var(--green-400)] transition-colors"
              >
                <span className="material-symbols-outlined text-xs">add</span> Create Scenario
              </Link>
            </div>
          ) : (
            <div className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-lg overflow-hidden">
              <div className="divide-y divide-[var(--border)]">
                {myScenarios.map((s) => {
                  const sc = statusColor(s.status);
                  return (
                    <Link
                      key={s.id}
                      href={`/dashboard/scenarios/${s.id}`}
                      className="flex items-center justify-between px-4 py-3 hover:bg-[var(--bg-elevated)] transition-colors"
                    >
                      <div className="min-w-0 flex-1">
                        <div className="text-xs font-medium text-[var(--text-primary)] truncate">{s.name}</div>
                        <div className="text-[10px] text-[var(--text-tertiary)] mt-0.5">
                          {s.scenarioInterventions.length} interventions
                          {s.totalProjectedTempReductionC != null &&
                            ` · -${s.totalProjectedTempReductionC.toFixed(1)}°C`}
                        </div>
                      </div>
                      <span
                        className="ml-3 shrink-0 text-[10px] font-semibold uppercase tracking-[0.05em] border rounded px-1.5 py-0.5"
                        style={{ color: sc.color, backgroundColor: sc.bg, borderColor: sc.border }}
                      >
                        {s.status.replace(/_/g, ' ')}
                      </span>
                    </Link>
                  );
                })}
              </div>
            </div>
          )}
        </div>

        {/* My Interventions */}
        <div>
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-1.5">
              <span
                className="material-symbols-outlined text-[var(--text-tertiary)] text-sm"
                style={{ fontVariationSettings: "'FILL' 1" }}
              >
                construction
              </span>
              <h2 className="text-[11px] font-medium uppercase tracking-[0.06em] text-[var(--text-tertiary)]">
                My Interventions
              </h2>
            </div>
            <Link
              href="/dashboard/interventions"
              className="text-[11px] text-[var(--text-tertiary)] hover:text-[var(--text-primary)] transition-colors"
            >
              View all →
            </Link>
          </div>

          {myInterventions.length === 0 ? (
            <div className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-lg p-6 text-center">
              <span
                className="material-symbols-outlined text-2xl text-[var(--text-tertiary)]"
                style={{ fontVariationSettings: "'FILL' 1" }}
              >
                construction
              </span>
              <p className="mt-2 text-xs text-[var(--text-secondary)]">No interventions proposed yet.</p>
              <Link
                href="/dashboard/interventions"
                className="mt-3 inline-flex items-center gap-1 h-8 px-3 text-xs font-medium bg-[var(--green-500)] text-white rounded-md hover:bg-[var(--green-400)] transition-colors"
              >
                <span className="material-symbols-outlined text-xs">add</span> Add Intervention
              </Link>
            </div>
          ) : (
            <div className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-lg overflow-hidden">
              <div className="divide-y divide-[var(--border)]">
                {myInterventions.map((inv) => {
                  const sc = statusColor(inv.status);
                  return (
                    <div key={inv.id} className="flex items-center justify-between px-4 py-3">
                      <div className="min-w-0 flex-1">
                        <div className="text-xs font-medium text-[var(--text-primary)] truncate">{inv.name}</div>
                        <div className="text-[10px] text-[var(--text-tertiary)] mt-0.5">
                          {inv.neighborhood?.name ?? 'City-wide'} ·{' '}
                          {inv.estimatedTempReductionC != null
                            ? `-${inv.estimatedTempReductionC.toFixed(1)}°C`
                            : 'Pending'}{' '}
                          {inv.estimatedCostUsd != null &&
                            `· $${Math.round(inv.estimatedCostUsd).toLocaleString()}`}
                        </div>
                      </div>
                      <span
                        className="ml-3 shrink-0 text-[10px] font-semibold uppercase tracking-[0.05em] border rounded px-1.5 py-0.5"
                        style={{ color: sc.color, backgroundColor: sc.bg, borderColor: sc.border }}
                      >
                        {inv.status.replace(/_/g, ' ')}
                      </span>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* My Reports */}
      {myReports.length > 0 && (
        <div>
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-1.5">
              <span
                className="material-symbols-outlined text-[var(--text-tertiary)] text-sm"
                style={{ fontVariationSettings: "'FILL' 1" }}
              >
                assessment
              </span>
              <h2 className="text-[11px] font-medium uppercase tracking-[0.06em] text-[var(--text-tertiary)]">
                My Reports
              </h2>
            </div>
            <Link
              href="/dashboard/reports"
              className="text-[11px] text-[var(--text-tertiary)] hover:text-[var(--text-primary)] transition-colors"
            >
              View all →
            </Link>
          </div>
          <div className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-lg overflow-hidden">
            <div className="divide-y divide-[var(--border)]">
              {myReports.map((r) => (
                <div key={r.id} className="flex items-center justify-between px-4 py-3">
                  <div className="min-w-0 flex-1">
                    <div className="text-xs font-medium text-[var(--text-primary)] truncate">{r.title}</div>
                    <div className="text-[10px] text-[var(--text-tertiary)] mt-0.5">
                      {r.type} · {new Date(r.generatedAt).toLocaleDateString()}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
      </GSAPWrapper>

      {/* Quick actions */}
      <GSAPWrapper animation="slideUp" delay={0.4} duration={0.5}>
      <div>
        <div className="flex items-center gap-1.5 mb-3">
          <span
            className="material-symbols-outlined text-[var(--text-tertiary)] text-sm"
            style={{ fontVariationSettings: "'FILL' 1" }}
          >
            bolt
          </span>
          <h2 className="text-[11px] font-medium uppercase tracking-[0.06em] text-[var(--text-tertiary)]">
            Quick Actions
          </h2>
        </div>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          {[
            { label: 'Open Map', href: '/map', icon: 'map', desc: 'Explore city heat zones' },
            { label: 'Neighborhoods', href: '/dashboard/neighborhoods', icon: 'location_city', desc: 'View & manage areas' },
            { label: 'New Scenario', href: '/dashboard/scenarios/new', icon: 'add_circle', desc: 'Plan interventions' },
            { label: 'Reports', href: '/dashboard/reports', icon: 'assessment', desc: 'Download council briefs' },
          ].map((action) => (
            <Link
              key={action.href}
              href={action.href}
              className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-lg p-4 hover:border-[var(--border-strong)] hover:bg-[var(--bg-elevated)] transition-colors group"
            >
              <span
                className="material-symbols-outlined text-[var(--green-400)] text-xl mb-2 block"
                style={{ fontVariationSettings: "'FILL' 1" }}
              >
                {action.icon}
              </span>
              <div className="text-xs font-semibold text-[var(--text-primary)]">{action.label}</div>
              <div className="text-[10px] text-[var(--text-tertiary)] mt-0.5">{action.desc}</div>
            </Link>
          ))}
        </div>
      </div>
      </GSAPWrapper>
    </div>
  );
}
